### ISSUE TITLE
ConnectorNotFoundError: Connector not found

### ISSUE THREAD

**Issue by elevenliu123456** [kolirt/vue-web3-auth#10]
When I use the switchChain method, the following error occurs. How to solve it?
switchChain ConnectorNotFoundError: Connector not found
Below is my code：
const chains = getAvailableChains()
       
 switchChain(chains[3]).then(res => {
      console.log('switchChain', res)
 }).catch((err) => {
      console.log('switchChain', err)
 })

**Comment by kolirt** [comment]
> When I use the switchChain method, the following error occurs. How to solve it? switchChain ConnectorNotFoundError: Connector not found Below is my code： const chains = getAvailableChains()
> 
> switchChain(chains[3]).then(res => { console.log('switchChain', res) }).catch((err) => { console.log('switchChain', err) })

Show me this part of the code https://github.com/kolirt/vue-web3-auth/blob/v2/examples/vite/src/main.ts#L10

**Comment by elevenliu123456** [comment]
> > When I use the switchChain method, the following error occurs. How to solve it? switchChain ConnectorNotFoundError: Connector not found Below is my code： const chains = getAvailableChains()
> > switchChain(chains[3]).then(res => { console.log('switchChain', res) }).catch((err) => { console.log('switchChain', err) })
> 
> Show me this part of the code https://github.com/kolirt/vue-web3-auth/blob/v2/examples/vite/src/main.ts#L10

`app.use(createWeb3Auth({
    projectId: 'xxxxxxxxxxxxxxxxxxx',
    chains: [
        Chains.bsc,
        Chains.mainnet,
        Chains.polygon,
        Chains.polygonMumbai,
        Chains.sepolia
    ]
}))`

**Comment by kolirt** [comment]
@elevenliu123456  Can you make a repo with this issue to check? I can't reproduce this issue

**Comment by kolirt** [comment]
@elevenliu123456 You can make your test repo based on one of the [examples](https://github.com/kolirt/vue-web3-auth/tree/v2/examples)

**Comment by elevenliu123456** [comment]
> @elevenliu123456 You can make your test repo based on one of the [examples](https://github.com/kolirt/vue-web3-auth/tree/v2/examples)



> switchChain

Can you show me the code of how you use switchChain's method?

**Comment by kolirt** [comment]
> Can you show me the code of how you use switchChain's method?

[Switch chain](https://github.com/kolirt/vue-web3-auth?tab=readme-ov-file#switch-chain)
[Select chain via Web3Modal](https://github.com/kolirt/vue-web3-auth?tab=readme-ov-file#select-chain-via-web3modal)

**Comment by elevenliu123456** [comment]
> > Can you show me the code of how you use switchChain's method?
> 
> [Switch chain](https://github.com/kolirt/vue-web3-auth?tab=readme-ov-file#switch-chain) [Select chain via Web3Modal](https://github.com/kolirt/vue-web3-auth?tab=readme-ov-file#select-chain-via-web3modal)

I re-used the method in your link, and I can switch networks normally without reporting errors. However, it cannot properly activate the metamask app on the mobile phone. I need to manually switch to the metamask app to see the interaction of switching networks. What I want to know is, after I call switchChain(), can a confirmation prompt appear like calling connect(), and then let me switch to metamask?

**Comment by elevenliu123456** [comment]
> > > Can you show me the code of how you use switchChain's method?
> > 
> > 
> > [Switch chain](https://github.com/kolirt/vue-web3-auth?tab=readme-ov-file#switch-chain) [Select chain via Web3Modal](https://github.com/kolirt/vue-web3-auth?tab=readme-ov-file#select-chain-via-web3modal)
> 
> I re-used the method in your link, and I can switch networks normally without reporting errors. However, it cannot properly activate the metamask app on the mobile phone. I need to manually switch to the metamask app to see the interaction of switching networks. What I want to know is, after I call switchChain(), can a confirmation prompt appear like calling connect(), and then let me switch to metamask?

**Comment by elevenliu123456** [comment]
> > > > Can you show me the code of how you use switchChain's method?
> > > 
> > > 
> > > [Switch chain](https://github.com/kolirt/vue-web3-auth?tab=readme-ov-file#switch-chain) [Select chain via Web3Modal](https://github.com/kolirt/vue-web3-auth?tab=readme-ov-file#select-chain-via-web3modal)
> > 
> > 
> > I re-used the method in your link, and I can switch networks normally without reporting errors. However, it cannot properly activate the metamask app on the mobile phone. I need to manually switch to the metamask app to see the interaction of switching networks. What I want to know is, after I call switchChain(), can a confirmation prompt appear like calling connect(), and then let me switch to metamask?

![91241706154138_ pic](https://github.com/kolirt/vue-web3-auth/assets/137073351/77488f27-cf31-49fc-82b9-bf381f5a7a83)
like this, Give the user a confirmation prompt to switch to metamask or switch directly to metamask

**Comment by kolirt** [comment]
@elevenliu123456 I'm still researching this issue

**Comment by kolirt** [comment]
> I re-used the method in your link, and I can switch networks normally without reporting errors. However, it cannot properly activate the metamask app on the mobile phone. I need to manually switch to the metamask app to see the interaction of switching networks. What I want to know is, after I call switchChain(), can a confirmation prompt appear like calling connect(), and then let me switch to metamask?

the browser requests confirmation prompt to open an external wallet in the browser only for the first time
if speak about switchChain, it also throws a network change confirmation only once in metamask, then you can switch to this network without confirmation

for example, in a trust wallet, you give access to switching between chains in the first connection, after which you can switch between them without additional confirmations

**Comment by elevenliu123456** [comment]
> @elevenliu123456 I'm still researching this issue

Looking forward to your good news, thank you for your hard work

**Comment by kolirt** [comment]
> Looking forward to your good news, thank you for your hard work

I've answered above

**Comment by kolirt** [comment]
> Looking forward to your good news, thank you for your hard work

Hi, I've updated the dependencies and your issue is solved. Please upgrade to [2.3.0](https://github.com/kolirt/vue-web3-auth/releases/tag/v2.3.0) version and check

**Comment by elevenliu123456** [comment]
> > Looking forward to your good news, thank you for your hard work
> 
> Hi, I've updated the dependencies and your issue is solved. Please upgrade to [2.3.0](https://github.com/kolirt/vue-web3-auth/releases/tag/v2.3.0) version and check

Cool !
