### ISSUE TITLE
[Question]: How to get wallet type information？

### ISSUE THREAD

**Issue by liujin798006810** [kolirt/vue-web3-auth#11]
### Description

If I want to get the user's wallet type information, for example I log in through TP Wallet, how can I get the name TP Wallet?

**Comment by kolirt** [comment]
@liujin798006810 

Please upgrade to v2.1.1 version and check [this](https://github.com/kolirt/vue-web3-auth?tab=readme-ov-file#info-about-the-users-connected-wallet-and-wallet-type)

**Comment by elevenliu123456** [comment]
> @liujin798006810
> 
> Please upgrade to v2.1.1 version and check [this](https://github.com/kolirt/vue-web3-auth?tab=readme-ov-file#info-about-the-users-connected-wallet-and-wallet-type)

Cool~
