### ISSUE TITLE
[Question]:  Process of getting payment through this library?

### ISSUE THREAD

**Issue by AHMAD1812** [kolirt/vue-web3-auth#13]
### Description

I'm just reading documentation and stuck to get my web3 application take payment from user, I've connected wallet into the application but now I just want to take payment from it? If you have any code related to this, It will be of great help.

I'm new on web3 so Thank in advance for help.

**Comment by AHMAD1812** [comment]
When I'm using writecontract function, I'm getting this error:

Uncaught (in promise) SwitchChainError: An error occurred when attempting to switch chain.

Details: Cannot set properties of undefined (setting 'defaultChain')

**Comment by kolirt** [comment]
> When I'm using writecontract function, I'm getting this error:
> 
> Uncaught (in promise) SwitchChainError: An error occurred when attempting to switch chain.
> 
> Details: Cannot set properties of undefined (setting 'defaultChain')

Have you configured the package?

[Configuration](https://github.com/kolirt/vue-web3-auth?tab=readme-ov-file#configuration)

**Comment by kolirt** [comment]
> I'm just reading documentation and stuck to get my web3 application take payment from user, I've connected wallet into the application but now I just want to take payment from it? If you have any code related to this, It will be of great help.

The purpose of this package is to make it easier to access web3 for vue. The payment function is not the direct responsibility of this package, you need to develop this functionality yourself using the available functionality of this package
