### ISSUE TITLE
[Feature]: Contract deploy provider

### ISSUE THREAD

**Issue by leisureprog** [kolirt/vue-web3-auth#14]
### Describe the feature

Is it possible to add a provider so that I can specify it when completing a contract?

![carbon (1)](https://github.com/kolirt/vue-web3-auth/assets/153300677/45fd85ed-6225-4901-9a9e-fd255de81df9)

### Additional information

- [ ] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

**Comment by kolirt** [comment]
Hello. What package are you importing ContractFactory from?

**Comment by leisureprog** [comment]
ethers.js

**Comment by kolirt** [comment]
> ethers.js

I don't know when I'll have time to research this issue and help u
Try this https://1.x.wagmi.sh/core/actions/getPublicClient, hope it helps you solve your problem

**Comment by leisureprog** [comment]
I only need to get a Sgner from your library.

**Comment by kolirt** [comment]
> I only need to get a Sgner from your library.

Can u check if [getWalletClient from wagmi](https://1.x.wagmi.sh/core/actions/getWalletClient) works for u case?
