### ISSUE TITLE
How to switch to metamask app when I use sendTransaction method on mobile phone?

### ISSUE THREAD

**Issue by liujin798006810** [kolirt/vue-web3-auth#16]
### Description

How to switch to metamask app when I use sendTransaction method on mobile phone?
Just like calling the connect method

**Comment by kolirt** [comment]
> How to switch to metamask app when I use sendTransaction method on mobile phone? Just like calling the connect method

It should be automatic

**Comment by liujin798006810** [comment]
> > How to switch to metamask app when I use sendTransaction method on mobile phone? Just like calling the connect method
> 
> It should be automatic

But when I execute the sendTransaction method on the mobile browser, why doesn't it automatically switch to the metamask app?

**Comment by kolirt** [comment]
> But when I execute the sendTransaction method on the mobile browser, why doesn't it automatically switch to the metamask app?

Hi, I've updated the dependencies and your issue is solved. Please upgrade to [2.3.0](https://github.com/kolirt/vue-web3-auth/releases/tag/v2.3.0) version and check

**Comment by elevenliu123456** [comment]
> > But when I execute the sendTransaction method on the mobile browser, why doesn't it automatically switch to the metamask app?
> 
> Hi, I've updated the dependencies and your issue is solved. Please upgrade to [2.3.0](https://github.com/kolirt/vue-web3-auth/releases/tag/v2.3.0) version and check

So cool, bro.
