### ISSUE TITLE
[Feature]: Custom Tokens Support

### ISSUE THREAD

**Issue by mrnasil** [kolirt/vue-web3-auth#17]
### Describe the feature

https://docs.walletconnect.com/web3modal/vue/options#tokens

Can we add this feature?

### Additional information

- [ ] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

**Comment by kolirt** [comment]
@mrnasil 

Hi, please upgrade to version [2.3.1](https://github.com/kolirt/vue-web3-auth/releases/tag/v2.3.1).

You sent feature from walletconnect v3 docs, but this package depends on v2. So I implemented [tokenImages](https://docs.walletconnect.com/web3modal/v2/javascript/wagmi/options#tokenimages-optional) and [tokenContracts](https://docs.walletconnect.com/web3modal/v2/javascript/wagmi/options#tokencontracts-optional) from v2.

You need to pass these parameters when setupping the package:
```ts
app.use(createWeb3Auth({
  web3modalOptions: {
    tokenImages: {
      ETH: "/images/eth.webp",
      AVAX: "/images/avax.webp",
    },
    tokenContracts: {
      1: '0x1f9840a85d5af5bf1d1762f925bdaddc4201f984',
      137: '0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174'
    }
  }
}))

```
