### ISSUE TITLE
[Bug]: Error reported when calling writeContract()

### ISSUE THREAD

**Issue by elevenliu123456** [kolirt/vue-web3-auth#18]
### Version

v2.3.2

### Package configuration

createWeb3Auth({
    projectId: '',
    chains: [
        Chains.bsc,
        Chains.mainnet,
        Chains.polygon,
        Chains.avalanche,
        Chains.opBNB,
        Chains.polygonMumbai,
        Chains.sepolia,
        Chains.linea,
        Chains.opBNBTestnet,
        Chains.bscTestnet
    ]
})

### Steps to reproduce

try {
            const value = await writeContract({
                abi: FireFlyTaskAbi,
                address: '0x499Bb30C53BF8155E7231C1cA2e042C8D037c108',
                functionName: 'action',
                args: [1, 3, []]
            })
} catch (err) {
     console.log('actionErr', err)
}

### Describe the bug

When I called writeContract(), the following error occurred
TypeError: t.replace is not a function
![WechatIMG168](https://github.com/kolirt/vue-web3-auth/assets/137073351/7e9f5317-168d-4fba-8612-b61b2982ab36)

**Comment by kolirt** [comment]
@elevenliu123456 

Can u share `FireFlyTaskAbi`?

**Comment by elevenliu123456** [comment]
> @elevenliu123456
> 
> Can u share `FireFlyTaskAbi`?

{
        "inputs": [
            {
                "internalType": "uint256",
                "name": "id",
                "type": "uint256"
            },
            {
                "internalType": "uint256",
                "name": "teamId",
                "type": "uint256"
            },
            {
                "internalType": "bytes",
                "name": "data",
                "type": "bytes"
            }
        ],
        "name": "action",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function"
    },
This is the action method in the abi file

**Comment by elevenliu123456** [comment]
> @elevenliu123456
> 
> Can u share `FireFlyTaskAbi`?

After hard work, I have solved this problem by replacing the last parameter [ ] with "0x" and it will work normally, haha

**Comment by elevenliu123456** [comment]
> > @elevenliu123456
> > Can u share `FireFlyTaskAbi`?
> 
> After hard work, I have solved this problem by replacing the last parameter [ ] with "0x" and it will work normally, haha

But when I use ethers.js on the PC, it works normally if I pass [ ] as the last parameter.

**Comment by kolirt** [comment]
> After hard work, I have solved this problem by replacing the last parameter [ ] with "0x" and it will work normally, haha

Yes, u sent the wrong data format
