### ISSUE TITLE
[Question]: How to make transfers to three wallets in a single signature?

### ISSUE THREAD

**Issue by tingshuai** [kolirt/vue-web3-auth#24]
### Description

I need to make transfers to three wallets at the same time。Can you provide an example?

**Comment by kolirt** [comment]
@tingshuai 

Hello. You have to use a multi-sender smart contract, you couldn't do it with just simple transfer transactions
Unfortunately, I don't have an example to show you. But it should look something like this (you need to find a multisendr contract or publish it yourself and use it):
```
import { erc20ABI, writeContract } from '@kolirt/vue-web3-auth'

await writeContract({
  abi: erc20ABI, // multi-sender ABI
  address: '0x55d398326f99059fF775485246999027B3197955', // multi-sender contract address
  functionName: 'approve', // specific function for multisend 
  args: ['0x685B1ded8013785d6623CC18D214320b6Bb64759', 100] // some args for function
}).then(async (data) => {
  console.log('hash', data.hash)

  await data.wait()

  console.log('transaction successfully')
})
```

**Comment by kolirt** [comment]
@tingshuai 

You can check out the multisender code here https://github.com/devEmkiddo/Ether-MultiSender-Smart-Contract

**Comment by tingshuai** [comment]
**After some research, I roughly understand the work required to implement this feature. However, I still have a question: I want to approve only one signature to complete the batch transfer. According to the answer provided by ChatGPT, it seems I need to obtain the “signer”. To avoid any misunderstandings in my thought process, I will lay out my complete steps to make the question clearer.**

- Here is the [contract code](https://gist.github.com/tingshuai/a55b01a17472a296970accaa61f3acd5) I want to deploy.
- Below is the frontend code provided by ChatGPT to call the contract.
```javascript
import { ethers } from 'ethers';

// 合约ABI，包含batchTransfer和setCallCooldown等函数
const contractABI = [
  "function batchTransfer((address recipient, uint256 amount)[] calldata requests) external",
  "function setCallCooldown(uint256 _callCooldown) external",
];

// 合约地址（部署后得到）
const contractAddress = "YOUR_CONTRACT_ADDRESS";

// USDT地址
const usdtAddress = "USDT_CONTRACT_ADDRESS";

async function connectWallet() {
  // 检查是否安装了以太坊兼容的钱包（例如MetaMask）
  if (window.ethereum) {
    const provider = new ethers.providers.Web3Provider(window.ethereum);
    await provider.send("eth_requestAccounts", []);
    const signer = provider.getSigner();
    return { provider, signer };
  } else {
    console.error("No Ethereum wallet detected");
  }
}

// 批量转账函数
async function batchTransferExample() {
  try {
    const { provider, signer } = await connectWallet();

    // 合约实例
    const contract = new ethers.Contract(contractAddress, contractABI, signer);

    // 构建批量转账请求
    const transferRequests = [
      { recipient: "0x08849bc8fbd3f3b9a2956b8be6418377912ad096", amount: ethers.utils.parseUnits("1", 6) },  // 1 USDT
      { recipient: "0x5b3a57d9f33ee7c2fdde7fe03382efa65a691d5b", amount: ethers.utils.parseUnits("1", 6) }   // 1 USDT
    ];

    // 获取合约需要的USDT数量
    const totalAmount = transferRequests.reduce((acc, req) => acc.add(req.amount), ethers.BigNumber.from(0));

    // 实例化USDT合约
    const usdtContract = new ethers.Contract(usdtAddress, ["function transfer(address recipient, uint256 amount) external returns (bool)", "function approve(address spender, uint256 amount) external returns (bool)"], signer);

    // 批准批量转账合约花费指定数量的USDT
    const approveTx = await usdtContract.approve(contractAddress, totalAmount);
    await approveTx.wait();

    // 调用批量转账函数
    const tx = await contract.batchTransfer(transferRequests);
    const receipt = await tx.wait();

    console.log("Batch transfer successful:", receipt);
  } catch (error) {
    console.error("Batch transfer failed:", error);
  }
}
```

- ### **The question is, how can I get the "signer" in vue-web3-auth in the following code that I posted above?**

``` javascript
const { provider, signer } = await connectWallet();
```

**Comment by kolirt** [comment]
@tingshuai 

The code you sent can be rewritten for this library as follows
```
import { erc20ABI, writeContract } from '@kolirt/vue-web3-auth'

const contractABI = [
  "function batchTransfer((address recipient, uint256 amount)[] calldata requests) external",
  "function setCallCooldown(uint256 _callCooldown) external",
];
const contractAddress = "YOUR_CONTRACT_ADDRESS";
const usdtAddress = "USDT_CONTRACT_ADDRESS";
const transferRequests = [
      [ "0x08849bc8fbd3f3b9a2956b8be6418377912ad096", ethers.utils.parseUnits("1", 6) ],  // 1 USDT
      [ "0x5b3a57d9f33ee7c2fdde7fe03382efa65a691d5b",  ethers.utils.parseUnits("1", 6) ]   // 1 USDT
    ];
const totalAmount = transferRequests.reduce((acc, req) => acc.add(req[1]), ethers.BigNumber.from(0));

// call approve function in usdt contract
await writeContract({
  abi: erc20ABI,
  address: usdtAddress,
  functionName: 'approve',
  args:[contractAddress, totalAmount]
}).then(async (data) => {
  console.log('hash', data.hash)

  await data.wait()

  console.log('transaction successfully')
})

// call batchTransfer function in your contract
await writeContract({
  abi: contractABI,
  address: contractAddress,
  functionName: 'batchTransfer',
  args: transferRequests
}).then(async (data) => {
  console.log('hash', data.hash)

  await data.wait()

  console.log('transaction successfully')
})
```

Also I took a look at your contract and it looks problematic. Before you call a function in your contract, you give it permission to use your usdt, but your contract does not use this permission, but only works with its own usdt on its balance
If you want to transfer usdt to this contract to call this function, then this function has security issues. Between the time you send money to the contract and the function you want to trigger, someone else can trigger that function and steal your money
The contract needs to be modified and can't be used as it is
I hope you're aware of these risks

**Comment by tingshuai** [comment]
> Also I took a look at your contract...

- Thank you for the reminder. The feature has been implemented.
- I originally wanted users to complete the authorization and batch transfer with just one interaction with the wallet. After reviewing it repeatedly, I found that this approach is not feasible. I have decided to abandon it and switch to requiring users to interact twice (authorization and batch transfer) to complete the process.
- With the help of ChatGPT, I have completed the code modification. Could you help me check if there are any vulnerabilities?
- Finally, to show my appreciation, I will also make an additional payment.

**1. Here is the [contract code](https://gist.github.com/tingshuai/b1768d3bac2180fc55610effba14b2ca) I want to deploy.**
**2. Below is the frontend code:**
```javascript
  return writeContract({
    abi: erc20ABI,
    address: AllLayer2ChainsMsg[chain.value.name].usdtAddress,
    functionName: 'approve',
    args: [contractAddress, ethers.parseUnits('0.03', 6)]
  }).then(async (approveData) => {
    console.log('approveData', approveData)
    await approveData.wait();
    return writeContract({
      abi: contractABI,
      address: contractAddress, // token address 
      functionName: 'batchTransfer', // function name in smart contract
      args: [transfers] // recipient's address, amount
    })
  })
```

**Comment by kolirt** [comment]
@tingshuai 

Thank you I'm very grateful for your support

I have reviewed your contract. You are using approvs correctly. There are no vulnerabilities associated with approving

But I'm not so sure that you are using the preventRepeatedCalls modifier correctly. At least from the code above, I don't see any logical need for the modifier in your contract. Perhaps its use is necessary for your Dapp and everything is fine, then ignore this comment

**Comment by kolirt** [comment]
@tingshuai 

About approves. You are right, you need to approve to use tokens in one transaction and in another transaction, you need to use this approve. This can't be done in one transaction

**Comment by tingshuai** [comment]
Alright, thank you for all your support
