### ISSUE TITLE
default chain ?

### ISSUE THREAD

**Issue by furkanavc** [kolirt/vue-web3-auth#3]
Can we define the default chain?
https://docs.walletconnect.com/web3modal/vue/options It exists here but I couldn't manage to add it.

**Comment by kolirt** [comment]
> Can we define the default chain? https://docs.walletconnect.com/web3modal/vue/options It exists here but I couldn't manage to add it.

Hey. The first network specified will be the default.

```
createWeb3Auth({
    chains: [
        Chains.bsc, // bsc is default
        Chains.mainnet,
        Chains.polygon
    ],
})
```
What is your case for using the default network?

**Comment by furkanavc** [comment]
Oh okay, I got it. I was just trying to work on testnet and when I connected metamask it was changing my network but I wanted to work on testnet and I thought if I could change the default to testnet it would work :)
Thank you for the answer.

**Comment by kolirt** [comment]
> Oh okay, I got it. I was just trying to work on testnet and when I connected metamask it was changing my network but I wanted to work on testnet and I thought if I could change the default to testnet it would work :) Thank you for the answer.

You need to add a test network when configuring the package and then it won't switch
Like this:
```
createWeb3Auth({
    chains: [
        Chains.bscTestnet
    ],
})
```
