### ISSUE TITLE
An error is reported when the mobile phone is connected to the wallet

### ISSUE THREAD

**Issue by middleGpt** [kolirt/vue-web3-auth#5]
Error message ：Failed to launch 'wc:e544ea0cbd8a1b4614f46d073b3bf79cefe7cf13c4f55743071482602fd2437c@2?relay-protocol=irn&symKey=883668d107de38f0fc588cbc1b7cd5107b5c1b88e62e3d06b396a84c83df762e' because the scheme does not have a registered handler.

**Comment by kolirt** [comment]
> Error message ：Failed to launch 'wc:e544ea0cbd8a1b4614f46d073b3bf79cefe7cf13c4f55743071482602fd2437c@2?relay-protocol=irn&symKey=883668d107de38f0fc588cbc1b7cd5107b5c1b88e62e3d06b396a84c83df762e' because the scheme does not have a registered handler.

Show me some code so I can help you
