### ISSUE TITLE
WebSocket connection closed abnormally with code: 3000

### ISSUE THREAD

**Issue by GUOXINYU3** [kolirt/vue-web3-auth#6]
请问 报这个错是什么原因呢

**Comment by kolirt** [comment]
> 请问 报这个错是什么原因呢

Hi. Can u share code for debugging?

**Comment by kolirt** [comment]
> 请问 报这个错是什么原因呢

Try to check if you have the same problem with examples
https://github.com/kolirt/vue-web3-auth/tree/v2/examples
