### ISSUE TITLE
Approve button from the bridgeconnect not doing anything.

### ISSUE THREAD

**Issue by AHMAD1812** [kolirt/vue-web3-auth#7]
I just cloned the vue-cli-example and trying to create web login from it. I'm in initial phase but I'm facing a problem. When I try to login from bridge connect on the demo website it works but when i try to login from same code in my local it shows me approve or reject but approve is not working do i need to follow some steps?

**Comment by kolirt** [comment]
> I just cloned the vue-cli-example and trying to create web login from it. I'm in initial phase but I'm facing a problem. When I try to login from bridge connect on the demo website it works but when i try to login from same code in my local it shows me approve or reject but approve is not working do i need to follow some steps?

send me a repo with your code and instructions to reproduce the issue

**Comment by kolirt** [comment]
> bridge connect

what is this? i dont see bridge connect in the demo https://kolirt.github.io/vue-web3-auth/

![image](https://github.com/kolirt/vue-web3-auth/assets/11573343/b66985ec-93c3-415a-b636-029244640178)

**Comment by AHMAD1812** [comment]
Bridge connect is a mobile application which allow you to connect with walletconnect. So I'm just scanning QR from the modal in the application and it represents me address and other things in the demo website but with the same code its not working in local with my project id.

**Comment by AHMAD1812** [comment]
> send me a repo with your code and instructions to reproduce the issue

I'm using exactly your repository example for vue cli

**Comment by AHMAD1812** [comment]
I just found that it was the app issue, it works with the other wallet app.
