### ISSUE TITLE
The contract function "tokenIdToOwner" returned no data ("0x").

### ISSUE THREAD

**Issue by elevenliu123456** [kolirt/vue-web3-auth#8]
Using method readContract, the following error message appears:
ContractFunctionExecutionError: The contract function "tokenIdToOwner" returned no data ("0x").

This could be due to any of the following:
  - The contract does not have the function "tokenIdToOwner",
  - The parameters passed to the contract function may be invalid, or
  - The address is not a contract.
 
Contract Call:
  address:   0x926DDCb518a4F8403EfA6194A142D775852f4780
  function:  tokenIdToOwner(unit256)
  args:                    (45)

  Below is my code，I'm sure the parameters I passed are correct。

try {
            const res = await readContract({
                address: VITE_APP_NFT_STAKE_ADDRESS,
                abi: StakeABI,
                functionName: 'tokenIdToOwner',
                args: [tokenId.value]
            })
            console.log('tokenIdToOwner', res)
        } catch (err) {
            console.log(err)
        }

**Comment by kolirt** [comment]
> Using method readContract, the following error message appears: ContractFunctionExecutionError: The contract function "tokenIdToOwner" returned no data ("0x").
> 
> This could be due to any of the following:
> 
> * The contract does not have the function "tokenIdToOwner",
> * The parameters passed to the contract function may be invalid, or
> * The address is not a contract.
> 
> Contract Call: address: 0x926DDCb518a4F8403EfA6194A142D775852f4780 function: tokenIdToOwner(unit256) args: (45)
> 
> Below is my code，I'm sure the parameters I passed are correct。
> 
> try { const res = await readContract({ address: VITE_APP_NFT_STAKE_ADDRESS, abi: StakeABI, functionName: 'tokenIdToOwner', args: [tokenId.value] }) console.log('tokenIdToOwner', res) } catch (err) { console.log(err) }

Are you in the right network to make a request? Show how you configure the package via createWeb3Auth method

**Comment by elevenliu123456** [comment]
I am using the Mumbai polygon test network, but I did not configure Mumbai in main.js. Is this why I got the above error?

**Comment by kolirt** [comment]
> I am using the Mumbai polygon test network, but I did not configure Mumbai in main.js. Is this why I got the above error?

Yes. You must add network. Example:
```ts
const app = createApp({...})

app.use(createWeb3Auth({
  projectId: '', // generate here https://cloud.walletconnect.com/ and turn on 'Supports Sign v2'
  chains: [
    Chains.polygonMumbai
  ]
}))

```

**Comment by elevenliu123456** [comment]
> > I am using the Mumbai polygon test network, but I did not configure Mumbai in main.js. Is this why I got the above error?
> 
> Yes. You must add network. Example:
> 
> ```ts
> const app = createApp({...})
> 
> app.use(createWeb3Auth({
>   projectId: '', // generate here https://cloud.walletconnect.com/ and turn on 'Supports Sign v2'
>   chains: [
>     Chains.polygonMumbai
>   ]
> }))
> ```
Yes, according to what you said, I succeeded. Thank you very much brother!
