### ISSUE TITLE
[Feature]: how to call Wallet_watchAsset method?

### ISSUE THREAD

**Issue by leisureprog** [kolirt/vue-web3-auth#9]
Hello! I need to call the wallet_watchAsset method using the wallet connect provider. How can I do that?
![carbon](https://github.com/kolirt/vue-web3-auth/assets/153300677/7b17364a-1cb3-493e-b95c-194ff9213052)

**Comment by kolirt** [comment]
Hello. I'll add this today

**Comment by kolirt** [comment]
> Hello! I need to call the wallet_watchAsset method using the wallet connect provider. How can I do that? 

Please upgrade to v2.1.0 version and check the [readme](https://github.com/kolirt/vue-web3-auth?tab=readme-ov-file#watchasset)
